apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-deployment
  labels:
    app: app-transaction
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: app-transaction
  template:
    metadata:
      labels:
        app: app-transaction
    spec:
      containers:
      - name: app-transaction
        image: gallo9923/app-transaction
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: app-transaction-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: app-transaction
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8082
  