apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: transaction-db-replicaset
  labels:
    app: transaction-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-db
  template:
    metadata:
      labels:
        app: transaction-db
    spec:
      containers:
      - name: transaction-db
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: transaction-db-secret
              key: database_user  
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: transaction-db-secret
              key: database_password
---
apiVersion: v1
kind: Service
metadata:
  name: db-transaction-clusterip-service
spec:
  selector:
    app: transaction-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017