apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: invoice-db-replicaset
  labels:
    app: invoice-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: invoice-db
  template:
    metadata:
      labels:
        app: invoice-db
    spec:
      containers:
      - name: invoice-db
        image: gallo9923/app-invoice-db
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: db-invoice-clusterip-service
spec:
  selector:
    app: invoice-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432